### ISSUE TITLE
[Question] How to access the CacheBase through the Java wrapper ?

### ISSUE THREAD

**Issue by dkgs** [bbopt/nomad#143]
Hi,

In order to get the best feasible solution, I get that we must request the cache with `NOMAD::CacheBase::getInstance()->findBestFeas(bf, NOMAD::Point(n), NOMAD::EvalType::BB,NOMAD::ComputeType::STANDARD, nullptr);`
However, I don't find any class / static function that permits this request from jNomad in the generated classes by swig.

Am I missing something, or is there another way to get the results ?

**Comment by ctribes** [comment]
You are right, it is not available in jNomad. It has been overseen!
Interfacing the CacheBase findBestFeas and findBestInfeas from Nomad is the best approach to get the optimization results. 
If you are willing to propose such modification, you can create a PullRequest to the develop branch (not the Master one). It will make its way into the next release.
Otherwise, I will use this issue, prioritize it and make a fix later.

**Comment by dkgs** [comment]
Ok, I'll dig into swig and propose something.

**Comment by ctribes** [comment]
Available for the next release
